This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React CI

on:
  push:
   branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # - uses: actions/checkout@v1
      # - run: npm install
      # - run: npm run build
      # - run: npm test
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and Build # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: build
