# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# # name: React CI

# # on:
# #   push:
# #     branches: ["main"]

# # jobs:
# #   build:
# #     runs-on: ubuntu-latest

# #     strategy:
# #       matrix:
# #         node-version: [16.x]
# #         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

# #     steps:
# #       - name: Checkout
# #         uses: actions/setup-node@v1

# #       - name: Install and build
# #         run: npm install
# #         run: npm run build

# #       - name: Deploy
# #         uses: pankajpuri/demodeployaction@v4
# #         with:
# #           branch: gh-pages
# #           folder: build

# name: React CI

# on:
#   push:
#     branches: ["main"]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [16.x]

#     steps:
#       - uses: actions/checkout@v1
#       - run: npm install
#       - run: npm run build
#       - run: npm test
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: React CI

# on:
#   push:
#     branches: ["main"]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [16.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#       - name: Checkout
#         uses: actions/setup-node@v1

#       - name: Install and build
#         run: npm install
#         run: npm run build

#       - name: Deploy
#         uses: pankajpuri/demodeployaction@v4
#         with:
#           branch: gh-pages
#           folder: build

name: React CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install and build
      - run: npm install
      - run: npm run build
      - run: npm test

      - name: Deploy
        uses: pankajpuri/demodeployaction@v1
        with:
          branch: gh-pages
          folder: build
